<?php
return array (
  'sitetitle' => '北京九州颐和文化中心',
  'sitetitle2' => '北京九州颐和',
  'siteurl' => 'http://localhost/waiku',
  'updown' => '1',
  'xgwz' => '1',
  'sitedescription' => '北京九州颐和文化中心',
  'sitekeywords' => '北京九州颐和文化中心,chinaihe.org',
  'sitelx' => 'Email:admin@163.com',
  'sitetcp' => '京ICP 123456',
  'tjnum' => '10',
  'phnum' => '10',
  'noticeid' => '5',
  'noticenum' => '5',
  'isping' => '1',
  'isshare' => '1',
  'pingoff' => '1',
  'bookoff' => '0',
  'mood' => '1',
  'sitelogo' => 'logo.png',
  'ishits' => '1',
  'iscopyfrom' => '1',
  'isauthor' => '1',
  'isvote' => '1',
  'ishomeimg' => '5',
  'mouseimg' => '1',
  'iszy' => '1',
  'id' => '1',
  'artlistnum' => '15',
  'rollnum' => '2',
  'postovertime' => '15',
  'urlmode' => '0',
  'suffix' => '0',
);
?>