$(function(){
	
	$("a[rel=shareGoods]").click(function(){
		var shareGoods = '<div id="J_ShareGoodsD" class="g-dialog sg-dialog" style="left: auto; right: 55px; top: 41px; display: block; "><div class="content"><p class="title">将宝贝网址粘贴到下面框中：</p><form class="sg-form" id="shareGoods" action="api/findProduct"><div class="clearfix"><input class="base-input sg-input" name="url" value="" placeholder="http://" autocomplete="off"><input type="submit" id="J_GoodsUrlSubmit" class="url-sub bbl-btn" value="确定"></div><div class="text-tip" style="display: block; "></div></form><div class="sg-source"><p class="pt10 pb5">已支持网站（<a href="http://guang.com/contact" target="_blank">商家申请加入</a>）：</p><div class="source-list clearfix"><a class="icon-source icon-taobao" href="http://www.taobao.com/" target="_blank">淘宝网</a><a class="icon-source icon-tmall" href="http://www.tmall.com/" target="_blank">天猫商城</a><a class="icon-source icon-paipai" href="http://buy.qq.com/" target="_blank">QQ网购</a><a class="icon-source icon-mbaobao" href="http://www.mbaobao.com/" target="_blank">麦包包</a><a class="icon-source icon-vancl" href="http://www.vancl.com/" target="_blank">凡客诚品</a></div></div><div class="tipbox-up" style="left: 353px; "><em>◆</em><span>◆</span></div><a class="close" href="javascript:;"></a></div></div>'
//		alert("test");
		$("body").append(shareGoods+'<div class="clearfix"><input class="base-input sg-input" name="url" value="" placeholder="http://" autocomplete="off" /><input type="submit" id="J_GoodsUrlSubmit" class="bbl-btn url-sub" value="\u786e\u5b9a" /></div><div class="text-tip"></div></form><div class="sg-source"><p class="pt10 pb5">\u5df2\u652f\u6301\u7f51\u7ad9\uff08<a href="http://guang.com/contact" target="_blank">\u5546\u5bb6\u7533\u8bf7\u52a0\u5165</a>\uff09\uff1a</p><div class="source-list clearfix"><a class="icon-source icon-taobao" href="http://www.taobao.com/" target="_blank">\u6dd8\u5b9d\u7f51</a><a class="icon-source icon-tmall" href="http://www.tmall.com/" target="_blank">\u5929\u732b\u5546\u57ce</a><a class="icon-source icon-paipai" href="http://buy.qq.com/" target="_blank">QQ\u7f51\u8d2d</a><a class="icon-source icon-mbaobao" href="http://www.mbaobao.com/" target="_blank">\u9ea6\u5305\u5305</a><a class="icon-source icon-vancl" href="http://www.vancl.com/" target="_blank">\u51e1\u5ba2\u8bda\u54c1</a></div></div><div class="tipbox-up"><em>\u25c6</em><span>\u25c6</span></div><a class="close" href="javascript:;"></a></div></div>');
	});
	
	var back = '<div class="dialog-content"><div class="hd"><h3>嗯~ 就是它吧</h3></div><div class="bd clearfix"><form id="J_GoodsPubForm" action="/ugc/api/saveProduct" method="POST"><div class="form-row"><label>宝贝名称：</label><span class="goodsNm">【风扇节】佳星电风扇 办公桌电扇 学生迷你台式小风扇 海风系列</span></div><div class="form-row"><label>评论一下：</label><textarea class="base-txa" name="proComment" placeholder="喜欢它什么呢？"></textarea></div><div class="form-row"><label>宝贝标签：</label><div class="inlineblock"><input type="text" class="base-input" name="tags" value=""><p class="pt5 gc">多个标签用空格、中文或英文逗号隔开</p></div></div><div class="form-row clearfix"><label>宝贝图片：</label><div class="goods-gallery"><div class="gallery-bd"><div class="items"><ul><li><a href="javascript:;"><img src="http://img04.taobaocdn.com/bao/uploaded/i4/T1grPcXdJhXXaWdVc._111105.jpg_310x310.jpg" alt=""></a><i></i></li><li><a href="javascript:;"><img src="http://img03.taobaocdn.com/imgextra/i3/820476625/T2MQGjXXpbXXXXXXXX_!!820476625.jpg_310x310.jpg" alt=""></a><i></i></li><li><a href="javascript:;"><img src="http://img02.taobaocdn.com/imgextra/i2/820476625/T2mAKjXopaXXXXXXXX_!!820476625.jpg_310x310.jpg" alt=""></a><i></i></li><li><a href="javascript:;"><img src="http://img04.taobaocdn.com/imgextra/i4/820476625/T2LQKjXnBaXXXXXXXX_!!820476625.jpg_310x310.jpg" alt=""></a><i></i></li></ul></div></div><div class="gallery-ft clearfix"><span class="status">已选 <em>0</em> 张</span><span class="errc"></span><div class="gallery-pagin"><a href="javascript:;" class="sgr-btn prev disabled">上页</a><span class="num-box"><em class="curP">1</em>/<em class="totalP">1</em></span><a href="javascript:;" class="sgr-btn next disabled">下页</a></div><a href="javascript:;" id="J_AddPicBtn" class="ap-btn sgr-btn" style="display: none; ">上传本地图片</a></div></div></div><div class="goods-act"><div class="clearfix"><a class="bbl-btn" id="J_GoodsPub" href="javascript:;">发布</a><label class="fl mt15 ml15 gc6"><input type="checkbox" name="tomyfav"> 加入我喜欢的宝贝</label></div><div class="errc mt10"></div></div></form></div><a class="close" href="javascript:;"></a></div>';
	
	$("#J_GoodsUrlSubmit").click(function() {
	    var jsonuserinfo = $.toJSON($('#shareGoods').serializeObject());   
	    alert(jsonuserinfo);  
	    jQuery.ajax( {   
		type : 'GET',   
		contentType : 'application/json',   
		url : 'api/findProduct',   
		data : jsonuserinfo,   
		dataType : 'json',   
		success : function(data) {
			if (data && data.success == "true") {
	            $("#J_ShareGoodsD").hide();
	            $("body").appen(back);
	      	}
		},   
		error : function(data) {
			alert("error")   
		}   
		});
	});   
	
	
//	var back = '<div class="dialog-content"><div class="hd"><h3>嗯~ 就是它吧</h3></div><div class="bd clearfix"><form id="J_GoodsPubForm" action="/ugc/api/saveProduct" method="POST"><div class="form-row"><label>宝贝名称：</label><span class="goodsNm">【风扇节】佳星电风扇 办公桌电扇 学生迷你台式小风扇 海风系列</span></div><div class="form-row"><label>评论一下：</label><textarea class="base-txa" name="proComment" placeholder="喜欢它什么呢？"></textarea></div><div class="form-row"><label>宝贝标签：</label><div class="inlineblock"><input type="text" class="base-input" name="tags" value=""><p class="pt5 gc">多个标签用空格、中文或英文逗号隔开</p></div></div><div class="form-row clearfix"><label>宝贝图片：</label><div class="goods-gallery"><div class="gallery-bd"><div class="items"><ul><li><a href="javascript:;"><img src="http://img04.taobaocdn.com/bao/uploaded/i4/T1grPcXdJhXXaWdVc._111105.jpg_310x310.jpg" alt=""></a><i></i></li><li><a href="javascript:;"><img src="http://img03.taobaocdn.com/imgextra/i3/820476625/T2MQGjXXpbXXXXXXXX_!!820476625.jpg_310x310.jpg" alt=""></a><i></i></li><li><a href="javascript:;"><img src="http://img02.taobaocdn.com/imgextra/i2/820476625/T2mAKjXopaXXXXXXXX_!!820476625.jpg_310x310.jpg" alt=""></a><i></i></li><li><a href="javascript:;"><img src="http://img04.taobaocdn.com/imgextra/i4/820476625/T2LQKjXnBaXXXXXXXX_!!820476625.jpg_310x310.jpg" alt=""></a><i></i></li></ul></div></div><div class="gallery-ft clearfix"><span class="status">已选 <em>0</em> 张</span><span class="errc"></span><div class="gallery-pagin"><a href="javascript:;" class="sgr-btn prev disabled">上页</a><span class="num-box"><em class="curP">1</em>/<em class="totalP">1</em></span><a href="javascript:;" class="sgr-btn next disabled">下页</a></div><a href="javascript:;" id="J_AddPicBtn" class="ap-btn sgr-btn" style="display: none; ">上传本地图片</a></div></div></div><div class="goods-act"><div class="clearfix"><a class="bbl-btn" id="J_GoodsPub" href="javascript:;">发布</a><label class="fl mt15 ml15 gc6"><input type="checkbox" name="tomyfav"> 加入我喜欢的宝贝</label></div><div class="errc mt10"></div></div></form></div><a class="close" href="javascript:;"></a></div>';
});