<?php
return array (
  'sitetitle' => '~sitetitle~',
  'sitetitle2' => '~sitetitle2~',
  'siteurl' => '~baseurl~',
  'updown' => '1',
  'xgwz' => '1',
  'sitedescription' => '~sitetitle2~',
  'sitekeywords' => '~sitetitle~',
  'sitelx' => 'Email:admin@waikucms.com 站长QQ:634150845',
  'sitetcp' => '移ICP备123456',
  'tjnum' => '10',
  'phnum' => '10',
  'noticeid' => '5',
  'noticenum' => '5',
  'isping' => '1',
  'isshare' => '1',
  'pingoff' => '1',
  'bookoff' => '0',
  'mood' => '1',
  'sitelogo' => 'logo.png',
  'ishits' => '1',
  'iscopyfrom' => '1',
  'isauthor' => '1',
  'isvote' => '1',
  'ishomeimg' => '5',
  'mouseimg' => '1',
  'iszy' => '1',
  'id' => '1',
  'artlistnum' => '15',
  'rollnum' => '2',
  'postovertime' => '15',
  'urlmode' => '0',
  'suffix' => '0',
);
?>